HOST_AGENT: {
  VISUAL_MODE: True, # Whether to use the visual mode
  REASONING_MODEL: False, # Whether the model is reasoning model. For OpenAI o1, o3, o4-mini, this field must be set to True.
  API_TYPE: "openai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  API_BASE: "https://api.openai.com/v1/chat/completions", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API.
  API_KEY: "sk-YOUR_API_KEY_HERE",  # The OpenAI API key, begin with sk-
  API_VERSION: "2025-02-01-preview", # "2024-02-15-preview" by default
  API_MODEL: "gpt-4o",  # The only OpenAI model by now that accepts visual input
}

APP_AGENT: {
  VISUAL_MODE: True, # Whether to use the visual mode
  REASONING_MODEL: False, # Whether the model is reasoning model. For OpenAI o1, o3, o4-mini, this field must be set to True.
  API_TYPE: "openai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  API_BASE: "https://api.openai.com/v1/chat/completions", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API.
  API_KEY: "sk-YOUR_API_KEY_HERE",  # The OpenAI API key, begin with sk-
  API_VERSION: "2025-02-01-preview", # "2024-02-15-preview" by default
  API_MODEL: "gpt-4o",  # The only OpenAI model by now that accepts visual input
}

EVALUATION_AGENT: {
  VISUAL_MODE: True, # Whether to use the visual mode
  REASONING_MODEL: False, # Whether the model is reasoning model. For OpenAI o1, o3, o4-mini, this field must be set to True.
  API_TYPE: "openai" , # The API type, "openai" for the OpenAI API, "aoai" for the AOAI API, 'azure_ad' for the ad authority of the AOAI API.  
  API_BASE: "https://api.openai.com/v1/chat/completions", # The the OpenAI API endpoint, "https://api.openai.com/v1/chat/completions" for the OpenAI API.
  API_KEY: "sk-YOUR_API_KEY_HERE",  # The OpenAI API key, begin with sk-
  API_VERSION: "2025-02-01-preview", # "2024-02-15-preview" by default
  API_MODEL: "gpt-4o",  # The only OpenAI model by now that accepts visual input
}

# Other configurations...
EXPERIENCE: {
  SAVE_EXPERIENCE: False,  # Whether to save the experience
  EXPERIENCE_SAVE_PATH: "./logs/experience/", # The path to save the experience
  LOAD_EXPERIENCE: False,  # Whether to load the experience
}

LOG_CONFIG: {
  LOG_LEVEL: "INFO",  # The log level
  LOG_PATH: "./logs/", # The path to save the logs
}
